Module not found: Can't resolve 'private-next-instrumentation-client'
https://nextjs.org/docs/messages/module-not-found

Error:  ⨯ ./node_modules/next/dist/lib/require-instrumentation-client.js:10:22
Module not found: Can't resolve 'private-next-instrumentation-client'

https://nextjs.org/docs/messages/module-not-found

 ○ Compiling /_error ...
Error:  ⨯ ./node_modules/next/dist/lib/require-instrumentation-client.js:10:22
Module not found: Can't resolve 'private-next-instrumentation-client'

https://nextjs.org/docs/messages/module-not-found

Error:  ⨯ ./node_modules/next/dist/lib/require-instrumentation-client.js:10:22
Module not found: Can't resolve 'private-next-instrumentation-client'

https://nextjs.org/docs/messages/module-not-found

 ⨯ ./node_modules/next/dist/lib/require-instrumentation-client.js:10:22
Module not found: Can't resolve 'private-next-instrumentation-client'

https://nextjs.org/docs/messages/module-not-found

Error:  ⨯ ./node_modules/next/dist/lib/require-instrumentation-client.js:10:22
Module not found: Can't resolve 'private-next-instrumentation-client'

https://nextjs.org/docs/messages/module-not-found

Error:  ⨯ ./node_modules/next/dist/lib/require-instrumentation-client.js:10:22
Module not found: Can't resolve 'private-next-instrumentation-client'

https://nextjs.org/docs/messages/module-not-found

Error:  ⨯ ./node_modules/next/dist/lib/require-instrumentation-client.js:10:22
Module not found: Can't resolve 'private-next-instrumentation-client'

https://nextjs.org/docs/messages/module-not-found

 ✓ Compiled /_error in 5.6s
 GET /?monospaceUid=0 500 in 54525ms
 GET /?monospaceUid=674674 500 in 53545ms
Error: FATAL: An unexpected Turbopack error occurred. Please report the content of /tmp/next-panic-86f75927112f474749b2ac04dc19f61f.log, along with a description of what you were doing when the error occurred, to https://github.com/vercel/next.js/issues/new?template=1.bug_report.yml

Error: [Error [TurbopackInternalError]: Next.js package not found

Debug info:
- Execution of get_entrypoints_with_issues_operation failed
- Execution of EntrypointsOperation::new failed
- Execution of Project::entrypoints failed
- Execution of AppProject::routes failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_loader_tree failed
- Execution of get_next_package failed
- Next.js package not found]

[?25h
<IDX> ✘ Preview shutdown unexpectedly
<IDX> Starting preview...
Waiting for your web server to start serving

> nextn@0.1.0 dev
> next dev --turbopack -p 9002 --port 9002 --hostname 0.0.0.0

Error: sh: line 1: next: command not found

<IDX> ✘ Preview failed to start
<IDX> Starting preview...
Waiting for your web server to start serving

> nextn@0.1.0 dev
> next dev --turbopack -p 9002 --port 9002 --hostname 0.0.0.0

Error: sh: line 1: next: command not found

<IDX> ✘ Preview failed to start

Try Again

Show Complete Logs